name = "cloudflare-gg"
main = "src/index.ts"
compatibility_date = "2024-04-14"

kv_namespaces = [
  { binding = "API_KEYS", id = "596b97eb2a5d4870b32ca82bece7ea25" },
  { binding = "INVITES", id = "7f6ea03e82734b378aa90e303b580073" },
]
